name: cosmos-api-docker

services:
  # 1. THE API
  cosmos-api-service:
    container_name: cosmos-api-service
    # Corrected image path based on your GitHub username
    image: ghcr.io/sandeepsagarpanjala/cosmos-api:latest
    restart: always
    # Docker reads this file into memory only when the container starts
    env_file: .env
    ports:
      - "3001:3000"
    depends_on:
      - cosmos-db-service
      - cosmos-redis-service

  # 2. THE DATABASE
  cosmos-db-service:
    container_name: cosmos-db-service
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: Roadmap
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # 3. THE CACHE
  cosmos-redis-service:
    container_name: cosmos-redis-service
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"

volumes:
  postgres_data:
