name: cosmos-api-docker

services:
  # 1. THE GATEKEEPER (Nginx)
  cosmos-proxy:
    image: nginx:alpine
    container_name: cosmos-proxy
    restart: always
    ports:
      - "8090:80" # This is the only "Front Door" people should use
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro # Added :ro for safety
    depends_on:
      - cosmos-api-service

  # 2. THE API
  cosmos-api-service:
    container_name: cosmos-api-service
    image: ghcr.io/sandeepsagarpanjala/cosmos-api:latest
    restart: always
    env_file: .env
    # CHANGE THIS:
    expose:
      - "3000" # Hidden from Mac, visible to Nginx
    depends_on:
      - cosmos-db-service
      - cosmos-redis-service

  # 3. THE DATABASE (Keep ports if you want to use a DB GUI like DBeaver from your Mac)
  cosmos-db-service:
    container_name: cosmos-db-service
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: Roadmap
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # 4. THE CACHE
  cosmos-redis-service:
    container_name: cosmos-redis-service
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"

volumes:
  postgres_data:
